const ADMIN_ROLES = Object.freeze({
  SUPER_ADMIN: "SuperAdmin",
  OPS_ADMIN: "OpsAdmin",
  FINANCE_ADMIN: "FinanceAdmin",
  SUPPORT_ADMIN: "SupportAdmin",
});

const PERMISSIONS = Object.freeze({
  DASHBOARD_READ: "dashboard.read",
  CUSTOMERS_MANAGE: "customers.manage",
  PARTNERS_APPROVE: "partners.approve",
  BOOKINGS_ASSIGN: "bookings.assign",
  PAYMENTS_REFUND: "payments.refund",
  PAYMENTS_PAYOUT: "payments.payout",
  DISPUTES_RESOLVE: "disputes.resolve",
  COUPONS_MANAGE: "coupons.manage",
  ANALYTICS_READ: "analytics.read",
  ROLES_READ: "roles.read",
  ZONES_MANAGE: "zones.manage",
  SETTINGS_MANAGE: "settings.manage",
  AUDIT_READ: "audit.read",
  COMPLAINTS_VIEW: "complaints.view",
  COMPLAINTS_UPDATE: "complaints.update",
});

const ROLE_PERMISSIONS = Object.freeze({
  [ADMIN_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ADMIN_ROLES.OPS_ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.PARTNERS_APPROVE,
    PERMISSIONS.BOOKINGS_ASSIGN,
    PERMISSIONS.DISPUTES_RESOLVE,
    PERMISSIONS.ZONES_MANAGE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.COMPLAINTS_VIEW,
    PERMISSIONS.COMPLAINTS_UPDATE,
  ],
  [ADMIN_ROLES.FINANCE_ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PAYMENTS_REFUND,
    PERMISSIONS.PAYMENTS_PAYOUT,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.AUDIT_READ,
  ],
  [ADMIN_ROLES.SUPPORT_ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.DISPUTES_RESOLVE,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.COMPLAINTS_VIEW,
    PERMISSIONS.COMPLAINTS_UPDATE,
  ],
});

const getPermissionsForRole = (role) => ROLE_PERMISSIONS[role] || [];

module.exports = {
  ADMIN_ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
};
