exports.BOOKING_STATUS = Object.freeze({
  PENDING_PAYMENT:    "PENDING_PAYMENT",
  SEARCHING:          "SEARCHING",
  ASSIGNED:           "ASSIGNED",
  PARTNER_ACCEPTED:   "PARTNER_ACCEPTED",
  ON_THE_WAY:         "ON_THE_WAY",
  ARRIVED:            "ARRIVED",
  IN_PROGRESS:        "IN_PROGRESS",
  COMPLETED:          "COMPLETED",
  QUEUED:             "QUEUED",
  CANCELLED:          "CANCELLED",
  PENDING_ASSIGNMENT: "PENDING_ASSIGNMENT",
});
